name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
          reviewdog_flags: -fail-level=any

      - name: Run RSpec and Code Coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 6392432f551415e66f3fe8cc290b3b1f117cf278b4925e9074ac684a22881e7b
        with:
          coverageCommand: bundle exec rspec
